name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "${internalVersion}"
load: STARTUP
api-version: 1.21.4
folia-supported: true
softdepend: [Vault]
author: EngineHub
website: https://enginehub.org/worldedit
commands:
  wegui:
    description: Open the WorldEdit menu
    usage: /<command> [brushes|tools|blocks|presets|settings|selection|generation|build|schematics|images]
    aliases: [/menu]
    permission: worldedit.gui
permissions:
  worldedit.gui:
    description: Allows opening the WorldEdit menus with /wegui or //menu. Each action still requires the permission of the WorldEdit command it runs.
    default: op
